export const seedProducts = [
  {
    id: 1,
    name: 'Rose Veil',
    price: 950,
    sizes: ['30ml', '50ml', '100ml'],
    image: './images/rose-veil.svg',
    category: 'Floral',
    occasions: ['Birthday', 'Gift', 'Personal use'],
    notes: ['Rose', 'Jasmine', 'Soft Musk'],
    description: 'A graceful floral composition with a luminous rose heart and a soft musky finish.',
    ingredients: 'Alcohol, Parfum, Aqua, Fragrance Allergens',
    availability: true,
    giftWrapping: true,
    rating: 4.8,
    reviews: 31,
    reviewSnippets: [{ rating: 5, author: 'Salma', text: 'Soft, elegant and easy to wear through the day.' }, { rating: 5, author: 'Nour', text: 'The rose note feels polished without becoming too sweet.' }]
  },
  {
    id: 2,
    name: 'Cedar Nocturne',
    price: 1250,
    sizes: ['50ml', '100ml'],
    image: './images/cedar-nocturne.svg',
    category: 'Woody',
    occasions: ['Wedding', 'Personal use', 'Gift'],
    notes: ['Cedarwood', 'Amber', 'Vetiver'],
    description: 'A warm woody scent built around dry cedar, amber warmth and smooth vetiver.',
    ingredients: 'Alcohol, Parfum, Aqua, Fragrance Allergens',
    availability: true,
    giftWrapping: true,
    rating: 4.7,
    reviews: 19,
    reviewSnippets: [{ rating: 5, author: 'Karim', text: 'Warm woods with a clean finish. Great for evening.' }, { rating: 4, author: 'Hana', text: 'The cedar stays present without feeling heavy.' }]
  },
  {
    id: 3,
    name: 'Amber Silk',
    price: 1350,
    sizes: ['30ml', '50ml'],
    image: './images/amber-silk.svg',
    category: 'Oriental',
    occasions: ['Wedding', 'Gift'],
    notes: ['Amber', 'Vanilla', 'Saffron'],
    description: 'A velvety oriental fragrance with creamy vanilla, amber depth and a saffron glow.',
    ingredients: 'Alcohol, Parfum, Aqua, Fragrance Allergens',
    availability: true,
    giftWrapping: true,
    rating: 4.9,
    reviews: 44,
    reviewSnippets: [{ rating: 5, author: 'Mariam', text: 'Velvety and distinctive. The saffron detail is beautiful.' }, { rating: 5, author: 'Rana', text: 'A rich choice for gifting and special occasions.' }]
  },
  {
    id: 4,
    name: 'Citrus Linen',
    price: 800,
    sizes: ['30ml', '50ml', '100ml'],
    image: './images/citrus-linen.svg',
    category: 'Fresh',
    occasions: ['Birthday', 'Personal use'],
    notes: ['Bergamot', 'Neroli', 'White Tea'],
    description: 'A crisp fresh fragrance that pairs sparkling citrus with neroli and airy white tea.',
    ingredients: 'Alcohol, Parfum, Aqua, Fragrance Allergens',
    availability: true,
    giftWrapping: false,
    rating: 4.6,
    reviews: 27,
    reviewSnippets: [{ rating: 5, author: 'Omar', text: 'Fresh, bright and very easy to wear during the day.' }, { rating: 4, author: 'Yara', text: 'The citrus opening feels clean and airy.' }]
  },
  {
    id: 5,
    name: 'Jasmine Letter',
    price: 1100,
    sizes: ['50ml', '100ml'],
    image: './images/jasmine-letter.svg',
    category: 'Floral',
    occasions: ['Wedding', 'Gift'],
    notes: ['Jasmine', 'Tuberose', 'Musk'],
    description: 'A polished white floral bouquet with a clean musky trail made for memorable occasions.',
    ingredients: 'Alcohol, Parfum, Aqua, Fragrance Allergens',
    availability: true,
    giftWrapping: true,
    rating: 4.8,
    reviews: 22,
    reviewSnippets: [{ rating: 5, author: 'Dina', text: 'A beautiful white floral with a soft trail.' }, { rating: 4, author: 'Hager', text: 'Jasmine comes through clearly without overpowering the musk.' }]
  },
  {
    id: 6,
    name: 'Santal Dune',
    price: 1450,
    sizes: ['50ml', '100ml'],
    image: './images/santal-dune.svg',
    category: 'Woody',
    occasions: ['Personal use', 'Gift'],
    notes: ['Sandalwood', 'Iris', 'Tonka'],
    description: 'A creamy sandalwood fragrance with powdery iris and a smooth tonka finish.',
    ingredients: 'Alcohol, Parfum, Aqua, Fragrance Allergens',
    availability: false,
    giftWrapping: true,
    rating: 4.9,
    reviews: 36,
    reviewSnippets: [{ rating: 5, author: 'Adam', text: 'Creamy sandalwood with a very smooth dry-down.' }, { rating: 5, author: 'Mai', text: 'A calm, polished scent that feels luxurious.' }]
  },
  {
    id: 7,
    name: 'Neroli Dawn',
    price: 900,
    sizes: ['30ml', '50ml'],
    image: './images/neroli-dawn.svg',
    category: 'Fresh',
    occasions: ['Birthday', 'Personal use', 'Gift'],
    notes: ['Neroli', 'Orange Blossom', 'Citrus'],
    description: 'Bright neroli and orange blossom with a clean citrus opening and a gentle dry-down.',
    ingredients: 'Alcohol, Parfum, Aqua, Fragrance Allergens',
    availability: true,
    giftWrapping: true,
    rating: 4.5,
    reviews: 16,
    reviewSnippets: [{ rating: 5, author: 'Sara', text: 'Bright neroli that feels effortless and clean.' }, { rating: 4, author: 'Tarek', text: 'A fresh everyday fragrance with a gentle finish.' }]
  },
  {
    id: 8,
    name: 'Velvet Oud',
    price: 1600,
    sizes: ['50ml', '100ml'],
    image: './images/velvet-oud.svg',
    category: 'Oriental',
    occasions: ['Wedding', 'Gift', 'Personal use'],
    notes: ['Oud', 'Rose', 'Patchouli'],
    description: 'A refined oud composition layered with rose and patchouli for a deep, polished presence.',
    ingredients: 'Alcohol, Parfum, Aqua, Fragrance Allergens',
    availability: true,
    giftWrapping: true,
    rating: 4.8,
    reviews: 29,
    reviewSnippets: [{ rating: 5, author: 'Laila', text: 'Deep, smooth and beautifully balanced with rose.' }, { rating: 5, author: 'Youssef', text: 'The oud feels refined rather than overwhelming.' }]
  }
];
